apiVersion: v1
kind: Service
metadata:
  name: {{ include "demojava.fullname" . }}
  labels:
    {{- include "demojava.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30719
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "demojava.selectorLabels" . | nindent 4 }}
